artifact_location: file:C:/Users/aimje/OneDrive/Documents/Labmentix/12_Capstone Project/mlflow_tracking/310950452537767840
creation_time: 1768886873818
experiment_id: '310950452537767840'
last_update_time: 1768886873818
lifecycle_stage: active
name: flight-price-prediction
